/*
-----------------------------------------------------------------------------
Filename:    HandGestureRecognizer.h
-----------------------------------------------------------------------------


This source file is generated by the
   ___                   _              __    __ _                  _ 
  /___\__ _ _ __ ___    /_\  _ __  _ __/ / /\ \ (_)______ _ _ __ __| |
 //  // _` | '__/ _ \  //_\\| '_ \| '_ \ \/  \/ / |_  / _` | '__/ _` |
/ \_// (_| | | |  __/ /  _  \ |_) | |_) \  /\  /| |/ / (_| | | | (_| |
\___/ \__, |_|  \___| \_/ \_/ .__/| .__/ \/  \/ |_/___\__,_|_|  \__,_|
      |___/                 |_|   |_|                                 
      Ogre 1.7.x Application Wizard for VC10 (July 2011)
      http://code.google.com/p/ogreappwizards/
-----------------------------------------------------------------------------
*/
#ifndef __HandGestureRecognizer_h_
#define __HandGestureRecognizer_h_
#include "StdAfx.h"
#include "KinectController.h"
#include "BaseApplication.h"
#if OGRE_PLATFORM == OGRE_PLATFORM_WIN32
#include "../res/resource.h"
#endif


class HandGestureRecognizer : public BaseApplication
{
public:
    HandGestureRecognizer(void);
    virtual ~HandGestureRecognizer(void);

protected:
	    // OIS::KeyListener
    virtual bool keyPressed( const OIS::KeyEvent &arg );
    virtual bool keyReleased( const OIS::KeyEvent &arg );

	virtual bool frameRenderingQueued(const Ogre::FrameEvent& evt);
	OgreBites::ParamsPanel* help;
	KinectController* mKinect;
	Ogre::OverlayElement* mDepthPanel;
	YesNoSlider* mQuitSlider;
    virtual void createScene(void);
};

#endif // #ifndef __HandGestureRecognizer_h_
